### ISSUE TITLE
gimp@2.10.20-1: File not found

### ISSUE THREAD

**Issue by NatoBoram** [lukesampson/scoop-extras#6440]
```yaml
Name: gimp
Description: GNU Image Manipulation Program
Version: 2.10.20-1
Website: https://www.gimp.org
License: GPL-3.0-only (https://spdx.org/licenses/GPL-3.0-only.html)
Manifest:
  C:\Users\natob\scoop\buckets\extras\bucket\gimp.json
Installed: No
Binaries:
  bin\gimp-console-2.10.exe gimp-console.exe gimp.exe bin\gimptool-2.0.exe gimptool.exe
```
```pwsh
Installing 'gimp' (2.10.20-1) [64bit]
Loading gimp-2.10.20-setup-1.exe from cache
Checking hash of gimp-2.10.20-setup-1.exe ... ok.
Extracting gimp-2.10.20-setup-1.exe ... done.
Running installer script...
Linking C:\ProgramData\scoop\apps\gimp\current => C:\ProgramData\scoop\apps\gimp\2.10.20-1
Creating shim for 'gimp-console-2.10'.
Creating shim for 'gimp-console'.
Creating shim for 'gimp'.
Creating shim for 'gimptool-2.0'.
Creating shim for 'gimptool'.
Creating shortcut for GIMP (gimp-2.10.exe)
Persisting etc\gimp
The filename, directory name, or volume label syntax is incorrect.
File not found - C:\ProgramData\scoop\apps\gimp\current\etc\gimp
Persisting share\gimp
The filename, directory name, or volume label syntax is incorrect.
File not found - C:\ProgramData\scoop\apps\gimp\current\share\gimp
'gimp' (2.10.20-1) was installed successfully!
```
![gimp-2 10_UOND79TyLk](https://user-images.githubusercontent.com/10495562/124402835-9e84ee00-dce7-11eb-9864-7548bc8c728c.png)
![gimp-2 10_IxCjq7uh1z](https://user-images.githubusercontent.com/10495562/124402837-a17fde80-dce7-11eb-8afc-b9e0a6c76b22.png)
